name: Cinema
configs:
  Production: release
  Staging: release
  Debug: debug
options:
  bundleIdOrefix: hits.projectstudy
  developmentLanguage: ru
packages:
  Alamofire:
    url: "https://github.com/Alamofire/Alamofire"
    majorVersion: 5.5.0
  SnapKit:
    url: "https://github.com/SnapKit/SnapKit"
    branch: develop
  KeychainSwift:
    url: "https://github.com/evgenyneu/keychain-swift?ysclid=lgc0sfaqau638640751"
    branch: master
targets:
  tasked:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    settings:
      base:
        INFOPLIST_FILE: tasked/Info.plist
targets:
  Cinema:
    sources:
      - Cinema
    dependencies:
      - package: Alamofire
      - package: SnapKit
      - package: KeychainSwift
    type: application
    platform: iOS
    deploymentTarget: "13.0"
